FROM ubuntu:lunar

WORKDIR /workspaces/real-time-handwritten-chat/

RUN apt-get update \
    && apt-get --no-install-recommends -y install git gnupg2 ca-certificates gcc g++ make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists
